services:
  app:
    build:
      context: ./app
    container_name: app
    expose:
      - "8080"
    ports:
      - "8080:8080"           # optional to reach directly from host
    labels:
      promtail.scrape: "true"

  sidecar:
    image: nginx:1.25
    container_name: sidecar
    volumes:
      - ./sidecar/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    expose:
      - "8081"
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend    # path to your React app folder
    container_name: frontend
    depends_on:
      - sidecar
      - app
    ports:
      - "3000:80"            # host:container
